name: E2E
on: [push, pull_request]

jobs:
  test:
    name: Run TestCafe
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Enter Url
        uses: actions/input-url@master

      - name: Set Page Url
        uses: allenevans/set-env@v1.0.0
        with:
          URL: 'https://oye-harry-react-hn.herokuapp.com/'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!

      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          version: latest
          args: "chrome tests/index-test.js"
        env:
          FIRST_NAME: Ankur-2
          LAST_NAME: Kakroo
