name: E2E
on: [push]

jobs:
  test:
    name: Run TestCafe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          version: latest
          args: "chrome tests/index-test.js"